# Generated by Django 3.2.5 on 2021-07-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0006_auto_20210726_0512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
